# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/svelty',
                'doc_host': 'https://fredguth.github.io',
                'git_url': 'https://github.com/fredguth/svelty',
                'lib_path': 'svelty'},
  'syms': {'svelty.core': {'svelty.core.foo': ('core.html#foo', 'svelty/core.py')}}}
