# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/util.ipynb.

# %% auto 0
__all__ = ['safe_not_equal']

# %% ../nbs/util.ipynb 3
def safe_not_equal(a,b):
    "Check if `a` is not equal to `b`"
    primitive = (int, str, bool, list, dict, tuple, set, frozenset)
    return (a != b) if isinstance(a, primitive) else True
