project:
  type: website
  preview:
    port: 2401
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    right:
      - icon: github
        href: "https://github.com/fastai/nbdev"
        
metadata-files: [nbdev.yml, sidebar.yml]